# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='favorNum',
            field=models.IntegerField(default=0),
        ),
    ]
